[package]
name = "nc-url-opener"
version = "0.3.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
url = "2"
