[package]
name = "nc-url-opener"
version = "0.2.1"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.9.1"
log = "0.4.17"
url = "2"
