name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { target: aarch64-unknown-linux-gnu, binary: nc-url-opener }
          - { target: armv7-unknown-linux-gnueabihf, binary: nc-url-opener }
          - { target: arm-unknown-linux-gnueabi, binary: nc-url-opener }
          - { target: x86_64-unknown-linux-gnu, binary: nc-url-opener }
          - { target: x86_64-unknown-linux-musl, binary: nc-url-opener }
          - { target: x86_64-pc-windows-gnu, binary: nc-url-opener.exe }

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform.target }}
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Build platform
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.platform.target }}

    - name: Package zip
      run: (cd target/${{ matrix.platform.target }}/release && zip - ${{ matrix.platform.binary }}) >nc-url-opener-${{ matrix.platform.target }}.zip

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform.target }}
        path: nc-url-opener-${{ matrix.platform.target }}.zip
        retention-days: 10

  publish:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: tmp

      - name: Starge artifacts
        run: |
          mkdir -p html/downloads
          mv tmp/*/*.zip html/downloads/
          find html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html