name: Release

on:
  workflow_dispatch:
    inputs:
      releaseLevel:
          type: choice
          required: true
          options:
            - major
            - minor
            - patch
            - release
            - rc
            - beta
            - alpha

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:

  release:
    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform.target }}

    - uses: dtolnay/rust-toolchain@stable
    - run: cargo install cargo-release
    - run: |
        git config --global user.email "joshkellendonk@gmail.com"
        git config --global user.name "Josh Kellendonk"
        cargo release ${{ inputs.releaseLevel }} --no-confirm --execute
