name: Release

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { target: aarch64-unknown-linux-gnu, binary: rht }
          - { target: armv7-unknown-linux-gnueabihf, binary: rht }
          - { target: arm-unknown-linux-gnueabi, binary: rht }
          - { target: x86_64-unknown-linux-gnu, binary: rht }
          - { target: x86_64-unknown-linux-musl, binary: rht }
          - { target: x86_64-pc-windows-gnu, binary: rht.exe }

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform.target }}

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install cross
      run: cargo install cross

    - name: Build ${{ matrix.platform.target }}
      run: cross build --release --target ${{ matrix.platform.target }}

    - name: Package zip
      run: (cd target/${{ matrix.platform.target }}/release && zip - ${{ matrix.platform.binary }}) >rht-${{ matrix.platform.target }}.zip

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform.target }}
        path: rht-${{ matrix.platform.target }}.zip
        retention-days: 10

  publish:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: tmp

      - name: Stage artifacts
        run: |
          mkdir -p html/downloads
          mv tmp/*/*.zip html/downloads/
          find html/downloads -type f | sed -re 's#html/(.*)#<a href="\1">\1</a><br />#' >html/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html