name: Release

on:
  workflow_dispatch:
    inputs:
      releaseLevel:
          type: choice
          required: true
          options:
            - major
            - minor
            - patch
            - release
            - rc
            - beta
            - alpha

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:

  release:
    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform.target }}

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.platform.target }}
        components: clippy

    - name: Install cross
      run: cargo install cargo-release

    - name: Build ${{ matrix.platform.target }}
      run: cargo release ${{ inputs.level }} --no-confirm --execute
