name: Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: dtolnay/rust-toolchain@stable
      with: { components: clippy }

    - run: cargo update
    - run: cargo build
    - run: cargo test

    - uses: peter-evans/create-pull-request@v3
      with:
        labels: auto-approve
        title: "chore: update dependencies"
        commit-message: |-
          chore(deps): upgrade dependencies
          
          Upgrades project dependencies. See details in [workflow run].
          
          [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}