name: Upgrade

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: dtolnay/rust-toolchain@stable
      with: { components: clippy }

    - run: cargo upgrade
    - run: cargo build
    - run: cargo test

    - uses: peter-evans/create-pull-request@v3
      with:
        title: "chore: upgrade dependencies"
